---

defaults: &defaults
  docker:
    - image: canonicalwebteam/dev
  working_directory: /srv

version: 2
jobs:
  lint-python:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Lint webapp with Flake8 and black
          command: flake8 canonicalwebteam tests setup.py && black --line-length 79 --check canonicalwebteam tests setup.py
  test-python:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip3 install coverage
      - run:
          name: Run tests with coverage
          command: |
            coverage run  --source canonicalwebteam ./setup.py test
            bash <(curl -s https://codecov.io/bash)
workflows:
  version: 2
  build:
    jobs:
      - lint-python
      - test-python
